name = "okrubik"
module = "github.com/rubikorg/okrubik"
flat = false
maxprocs = 0
Log = false

[[app]]
  name = "cli"
  path = "./cmd/okrubik"
  watch = false
  communicate = false

[[app]]
  name = "server"
  path = "./cmd/server"
  watch = true
  communicate = false

[x]
  [x.cli]
    command = "go run main.go"
    pwd = "cmd/okrubik"
  [x.debug]
    command = "go run main.go"
    pwd = "cmd/server"
  [x.testcli]
    command = "go test ./cmd/okrubik/..."
  [x.testsrv]
    command = "go test ./cmd/server/..."
