name = "okrubik"
module = "github.com/rubikorg/okrubik"
flat = false
maxprocs = 0
Log = false

[[app]]
  name = "cli"
  path = "./cmd/okrubik"
  watch = false
  communicate = false
  log = false

[[app]]
  name = "server"
  path = "./cmd/server"
  watch = true
  communicate = false
  log = false
  [app.store]
    dialect = "mongo"
    protocol = "mongodb"
    host = "localhost"
    port = 27017
    database = "riddler"

[x]
  [x.buildcli]
    command = "go build -o . cmd/okrubik/main.go"
  [x.cli]
    command = "go run main.go"
    pwd = "cmd/okrubik"
  [x.debug]
    command = "go run main.go"
    pwd = "cmd/server"
  [x.foo]
    command = "echo foo"
  [x.testcli]
    command = "go test -cover ./cmd/okrubik/..."
  [x.testsrv]
    command = "go test -cover ./cmd/server/..."
