port = 7000
host = "127.0.0.1"

[basic_auth]
username = "ash"
password = "ash"

[jwt_auth]
secret = "mysecret"

[basicMsgPasser]
name = "first3"

[cors]
allOrigins = true

[swagger]
title = "Rubik Server"
description = "This is the main server for Rubik and it's CLI tool. For `okrubik`!"
version = "1.0.1"
# termsOfService = "http://www.apache.org/licenses/LICENSE-2.0.html"