port = ":7000"

[basicguard]
username = "ash"
password = "ash"

[basicMsgPasser]
name = "first3"

[cors]
allOrigins = true

[swagger]
title = "Rubik Server"
description = "This is the main server for Rubik and it's CLI tool. For `okrubik`!"
version = "1.0.1"
# termsOfService = "http://www.apache.org/licenses/LICENSE-2.0.html"