name: CLI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'README.md'
    branches: [ master ]

jobs:

  test:
    name: Test Workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test CLI
      run: go test -v ./cmd/okrubik/...

    - name: Test Server
      run: go test -v ./cmd/server/...
